export class DTOConfProduct {
	Code: number = 0
	Barcode: string = ""
	BrandName: string = ""
	BuyerName: string = ""
	GroupIDCode1: string = ""
	GroupIDCode2: string = ""
	GroupIDCode3: string = ""
	GroupIDCode4: string = ""
	GroupIDCode5: string = ""
	GroupIDName1: string = ""
	GroupIDName2: string = ""
	GroupIDName3: string = ""
	GroupIDName4: string = ""
	GroupIDName5: string = ""
	ImageSetting: string = ""
	URLThumbImage: string = ""
	IsDate: boolean = false
	MakerName: string = ""
	OriginName: string = ""
	Poscode: string = ""
	ProductName: string = ""
	Alias: string = ""
	Status: number = 1
	StatusID: number = 0
	StatusName: string = "Đang kinh doanh"
	TypeData: number = 1
	UnitPrice: number = 0
	ListTag: string = "[]"
}

export class DTODetailConfProduct extends DTOConfProduct {
	BarcodeBase: string = ""
	BaseUnitName: string = ''
	BaseUnit: number = null
	BaseUnitH: number = null
	BaseUnitL: number = null
	BaseUnitW: number = null
	BaseUnitWeight: number = null
	Brand: number = null
	Buyer: number = null
	StatusBuyer: number = null
	BuyerStatusName: string = ""
	BuyerUnit: number = null
	BuyerUnitName: string = ""
	CartonBase: number = null
	CartonH: number = null
	CartonL: number = null
	CartonW: number = null
	CartonWeight: number = null
	CertificationLink: string = ""
	CertificationNo: string = ""
	DataAccessGroupID1: number = null
	DataAccessGroupID2: number = null
	DataAccessGroupIDName1: string = ""
	DataAccessGroupIDName2: string = ""
	DateDuration?: number = 0
	DateMinRate: number = 0
	FirstPO: string = ""
	GroupID: number = null
	GroupID1: number = null
	GroupID2: number = null
	GroupID3: number = null
	GroupID4: number = null
	GroupID5: number = null
	IMTaxCode: string = ""
	IMTaxRate: number = null
	InnInnerHerW: number = null
	InnerBase: number = null
	InnerL: number = null
	InnerW: number = null
	InnerH: number = null
	InnerWeight: number = null
	IsHachi24: boolean = false
	IsVATOut: boolean = false
	ListLabel: DTOLabel[] = []
	Maker: number = null
	Manufacturer: number = null
	ManufacturerName: string = ""
	Material: string = ''
	MinDisplay: number = null
	Origin: number = null
	PackageH: number = null
	PackageL: number = null
	PackageW: number = null
	PackageWeight: number = null
	PalletBase: number = null
	PalletH: number = null
	PalletL: number = null
	PalletW: number = null
	PalletWeight: number = null
	ProductNameEN: string = ''
	ProductNameJP: string = ''
	SellerUnit: number = null
	SellerUnitName: string = ""
	Shipper: number = null
	ShipperName: string = ""
	Supplier: number = null
	SupplierName: string = ''
	TaxID: string = ""
	TaxName: string = ""
	VAT: number = null
	VATInCode: string = ""
	VATInRate: number = null
	WHUnit: number = null
	WHUnitName: string = ""
	WebBrief1: string = ""
	WebBrief2: string = ''
	WebBrief3: string = ''
	WebDistributor: string = ''
	WebExpiredDate: string = ''
	WebGroupIDName1: string = ""
	WebGroupIDName2: string = ""
	WebGroupIDName3: string = ""
	WebGroupIDName4: string = ""
	WebGroupIDName5: string = ""
	WebImporter: string = ''
	WebIntroVN: string = ''
	WebLotDate: string = ''
	WebManufacturer: string = ''
	WebName: string = ''
	WebRemark: string = ''
	WebTechVN: string = ''
	WebUsesVN: string = ""
	MetaTitle: string = ""
	MetaKeyword: string = ""
	MetaDescription: string = ""
	MetaStatus: number = null
	MetaStatusName: string = ""
	MonthSale: number = null
	MonthQty: number = null
	BufferQty:number = null
	//todo
	IsAvatar: boolean = false//sau này bỏ
	IsHachi: boolean = false
	IsLapSon: boolean = false
	IsKYN: boolean = false
	Qty: number= 0
	Bid: number = 0
	AvgPrice: number = 0
	VATIn:number = 0
	AmountMonthSale:number = null
	QtyMonthSale:number = null
	QtyMore:number = null
	CommercialTerm: number = null
	CurrencyAvg: number = null
	CurrencyIn: number = null
}

export class DTOLabel {
	Code: number = 0
	Sticker: number = 0
	StickerName: string = ''
	Product: number = 0
	Company: number = 0
	Remark: string = ''
	ProductName1:string = ''
	ProductName2:string = ''
	Content1: string = ''
	Content2: string = ''
	Content3: string = ''
	Footer1: string = ''
	Footer2: string = ''

	LabelDescription: string = ''
	LabelName1: string = ''
	LabelName2: string = ''
	LabelType: string = ''
	Selectted: boolean = true
}