export class EnumLayout {
    static GetStaffInfo: string 
    static GetCompany: string 
    static GetModule: string 
    static GetPermission: string 
    static GetPermissionDLL: string 
    static GetListStore: string 
    static GetWarehouse: string 
    static GetListWarehouse: string 
    static GetListProduct: string 
    static GetProductByCode: string 
    static GetStockInWareHouse: string 
    static GetWebInCart: string 
    static UploadBanner: string 
    static RenameFile: string 
    static DeleteFile: string 
    static GetTemplate: string 
    static ImportExcel: string 
    static ImportExcelWithFunctionID: string 
    static ImportExcelOrders: string 
    static ImportOnlineOrderVAT: string 
    static GetListStatus: string 
    static UpdateAPIServices: string
    static UpdateListAPIServices: string
    static RegisterAdmin: string
    static URLPortal: string
    static SetFirebaseToken: string
    static GetListNotification: string
    static UpdateNotificationStatus: string
}