export class EnumPurchase {
    static GetListBrand: string
    static GetBrand: string
    static UpdateBrand: string
    static DeleteBrand: string
    static UpdateBrandStatus: string
    static MergeBrand: string
    static GetReports: string
    static ExportReport: string
    static GetDataDropdown: string
    static GetListReceivePartner: string
    static GetListReceiveOrder: string
    static GetReceiveOrder: string
    static UpdateOrderReceiving: string
    static GetListReceiveInvoice: string
    static GetReceiveInvoice: string
    static UpdateInvoiceReceiving: string
    static GetListReceiveProduct: string
    static GetReceiveProduct: string
    static UpdateProductReceiving: string
    static GetSupplier: string
    static UpdateSupplier: string
    static GetListSupplierContact: string
    static UpdateSupplierContact: string
    static DeleteSupplierContact: string
    static GetListPOProduct: string
    static GetListBuyedHistory: string
    static GetListChangePriceHistory: string
    static GetListReason: string
    static DeleteSupplier: string
    static GetListSupplierTree: string
    static GetTemplateEmail: string
    static UpdateTemplateEmail: string

    static GetListPriceRequest: string
    static GetPriceRequest: string
    static UpdatePriceRequest: string
    static DeletePriceRequest: string
    static UpdatePriceRequestStatus: string

    static GetListProductPriceRequest: string
    static GetProductPriceRequest: string
    static UpdateProductPriceRequest: string
    static UpdateProductPriceRequestStatus: string
    static DeleteProductPriceRequest: string
    static GetProductPriceRequestByCode: string
    static ImportExcelProductPriceRequest: string
    static ImportExcelPriceRequest: string
    static GetListCommercialTerm: string
    static GetListSupplier: string

    // PO Domestic
    static GetListOrderProduct: string
    static ImportOrderProduct: string
    static UpdateOrderProduct: string
    static GetListDomesticOrders: string
    static UpdateDomesticOrdersStatus: string
    static DeleteDemesticOrders: string
    static DeleteOrderProduct: string
    static GetDeliveryOrder: string
    static GetExcelAlbumn: string
    static PrintOrder: string
    static GetOrderProduct: string
    static PrintOrderDetail: string
    static UpdateDomesticOrder: string
    static GetDomesticOrder: string
    static GetListWareHouse: string
    static GetListOrderInvoice: string
    static DuplicatePOCancel: string
    static GenerateInvoice: string
    static GenerateInvoiceByVAT: string
    static UpdateInvoiceProduct: string
    static AddInvoiceProduct: string
    static UpdateDeliveryOrder: string
    static UpdateInvoice: string
    static UpdateInvoiceStatus: string
    static GetListProductNotIncludedInvoice: string
    static ImportExcelInvoice: string
    static GetListNewProductProposal: string
    // New Product Proposal
    static GetNewProductProposal: string
    static UpdateNewProductProposalStatus: string
    static UpdateNewProductProposal: string
    static DeleteNewProductProposal: string
    static DeleteProductImage: string
    static ImportExcelNewProductProposal: string
    static GetPromotionFolderDrillWithFile: string
    static UpdateProductImage: string
    static ExportDomesticOrdersExcel: string
    static ExportDomesticOrdersPDF: string
    static ExportOrderDetailsClientExcel: string
    static ExportOrderDetailsClientPDF: string
    static ExportPurchaseOrderReceivedExcel: string
    static DeleteInvoice: string
    static GetListTax: string
    static GetFolderWithFile: string

    // New Gift
    static GetListGift: string;
    static GetGift: string;
    static ImportExcelGift: string;
    static UpdateGift: string;
    static DeleteGift: string;
    static UpdateGiftStatus: string;
}
