import { LayoutPortalComponent } from "../layout-portal/layout-portal.component";

export const ModuleDataAdmin: Array<any> = [
    // //PORTAL
    // {
    //     Code: 'portal',
    //     ModuleID: 'portal', // cần bổ sung trường này để khi user vào portal service có thể tìm thấy module
    //     Name: 'Portal',
    //     Actived: false,
    //     Link: 'portal/portal001-exam-list',
    //     Path: 'portal',
    //     LoadChildren: () => import('../../p-portal/p-portal.module').then(m => m.PPortalModule),
    //     component: LayoutPortalComponent,
    //     ListMenu: [
    //         {
    //             Name: "Kiểm tra năng lực",
    //             Actived: false,
    //             Code: "portal001-exam-list",
    //             Link: "/portal/portal001-exam-list",
    //             Icon: "spell-check",
    //             Type: 'function',
    //             LstChild: [
    //                 {
    //                     Name: "Đợt đánh giá",
    //                     Actived: false,
    //                     Code: "portal001-exam-detail",
    //                     Link: "/portal/portal001-exam-detail",
    //                     Type: 'function',
    //                     LstChild: [],
    //                 }
    //             ],
    //         },
    //         {
    //             Name: "Phiếu lương",
    //             Actived: false,
    //             Code: "portal003-paycheck-detail",
    //             Link: "/portal/portal003-paycheck-detail",
    //             Icon: "dollar",
    //             Type: 'function',
    //             LstChild: [],
    //         },
    //         {
    //             Name: "Tra cứu chính sách",
    //             Actived: false,
    //             Code: "portal002-news-list",
    //             Link: "/portal/portal002-news-list",
    //             Icon: "circle-info",
    //             Type: 'function',
    //             LstChild: [
    //                 {
    //                     Name: "Chi tiết chính sách",
    //                     Actived: false,
    //                     Code: "portal002-news-detail",
    //                     Link: "/portal/portal002-news-detail",
    //                     Type: 'function',
    //                     LstChild: [],
    //                 },
    //             ],
    //         },
    //     ]
    // },
    //Enterprise
    {
        Code: 'dev',
        Name: 'DEVELOPER',
        Actived: true,
        Link: 'dev/dev001-company-list',
        Path: 'dev',
        LoadChildren: () => import('../../p-developer/p-developer.module').then(m => m.PDevelopModule),
        ListMenu: [{
            Name: "Cấu trúc hệ thống",
            Actived: false,
            Code: "sysStructure",
            Link: "/dev/dev001-company-list",
            Type: 'group',
            LstChild: [{
                Name: "Danh sách Công ty",
                Actived: false,
                Code: "dev001-company-list",
                Link: "/dev/dev001-company-list",
                Type: 'function',
                LstChild: [],
            }, {
                Name: "Cấu trúc hệ thống",
                Actived: false,
                Code: "dev002-system-list",
                Link: "/dev/dev002-system-list",
                Type: 'function',
                LstChild: [],
            }, {
                Name: "Danh sách API",
                Actived: false,
                Code: "dev003-api-list",
                Link: "/dev/dev003-api-list",
                Type: 'function',
                LstChild: [],
            },],
        },]
    },
    //DASHBOARD
    {
        Code: 'dashboard',
        Name: 'Dashboard',
        Actived: true,
        Link: 'dashboard/dashboard001-ecom',
        Path: 'dashboard',
        LoadChildren: () => import('../../p-dashboard/p-dashboard.module').then(m => m.PDashboardModule),
        ListMenu: [
            {
                Name: "Dashboard Ecom",
                Actived: false,
                Code: "dashboard001-ecom",
                Link: "/dashboard/dashboard001-ecom",
                Type: 'function',
                LstChild: [],
            },
        ]
    },
    //MARKETING
    {
        Code: 'mar',
        Name: 'Marketing',
        Actived: true,
        Link: 'marketing/mar001-banner',
        Path: 'marketing',
        LoadChildren: () => import('../../p-marketing/p-marketing.module').then(m => m.PMarketingModule),
        ListMenu: [
            // {
            //     Name: "Dashboard",
            //     Actived: false,
            //     Code: "mar-dashboard",
            //     Link: "/marketing/mar001-banner",
            //     Type: 'function',
            //     LstChild: [],
            // },
            {
                Name: "Khuyến mãi",
                Actived: false,
                Code: "mar-promotion",
                Link: "/marketing/mar001-discount-product",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Sản phẩm",
                        Actived: false,
                        Code: "mar001-discount-product",
                        Link: "/marketing/mar001-discount-product",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHI TIẾT KHUYẾN MÃI",
                            Actived: false,
                            Code: "mar001-discount-detail",
                            Link: "/marketing/mar001-discount-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    }, {
                        Name: "Combo - Giftset",
                        Actived: false,
                        Code: "mar002-discount-combo",
                        Link: "/marketing/mar002-discount-combo",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHI TIẾT CHƯƠNG TRÌNH",
                            Actived: false,
                            Code: "mar002-discount-combo-detail",
                            Link: "/marketing/mar002-discount-combo-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Hamper",
                        Actived: false,
                        Code: "mar019-discount-hamper",
                        Link: "/marketing/mar019-discount-hamper",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHI TIẾT CHƯƠNG TRÌNH",
                            Actived: false,
                            Code: "mar019-discount-hamper-detail",
                            Link: "/marketing/mar019-discount-hamper-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Quà tặng",
                        Actived: false,
                        Code: "mar021-discount-gift-list",
                        Link: "/marketing/mar021-discount-gift-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHI TIẾT CHƯƠNG TRÌNH QUÀ TẶNG",
                            Actived: false,
                            Code: "mar021-discount-gift-item",
                            Link: "/marketing/mar021-discount-gift-item",
                            Type: '',
                            LstChild: [],
                        },
                        {
                            Name: "CHI TIẾT CHƯƠNG TRÌNH QUÀ TẶNG",
                            Actived: false,
                            Code: "mar021-discount-gift-group",
                            Link: "/marketing/mar021-discount-gift-group",
                            Type: '',
                            LstChild: [],
                        },
                        {
                            Name: "CHI TIẾT CHƯƠNG TRÌNH QUÀ TẶNG",
                            Actived: false,
                            Code: "mar021-discount-gift-order",
                            Link: "/marketing/mar021-discount-gift-order",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                ],
            },
            {
                Name: "NỘI DUNG WEBSITE",
                Actived: false,
                Code: "mar-website",
                Link: "/marketing/mar003-news-product",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Bài viết sản phẩm",
                        Actived: false,
                        Code: "mar003-news-product",
                        Link: "/marketing/mar003-news-product",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Bài viết Sản phẩm",
                            Actived: false,
                            Code: "mar003-news-product-detail",
                            Link: "/marketing/mar003-news-product-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Quản lý banner",
                        Actived: false,
                        Code: "mar009-banner-list",
                        Link: "/marketing/mar009-banner-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHI TIẾT Banner",
                            Actived: false,
                            Code: "mar009-banner-detail",
                            Link: "/marketing/mar009-banner-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Blog",
                        Actived: false,
                        Code: "mar010-post-list",
                        Link: "/marketing/mar010-post-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHI TIẾT BLOG",
                            Actived: false,
                            Code: "mar010-post-detail",
                            Link: "/marketing/mar010-post-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Tin tức",
                        Actived: false,
                        Code: "mar011-news-list",
                        Link: "/marketing/mar011-news-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHI TIẾT TIN TỨC",
                            Actived: false,
                            Code: "mar011-news-detail",
                            Link: "/marketing/mar011-news-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Chính sách bán hàng",
                        Actived: false,
                        Code: "mar012-policy-list",
                        Link: "/marketing/mar012-policy-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHI TIẾT CHÍNH SÁCH",
                            Actived: false,
                            Code: "mar012-policy-detail",
                            Link: "/marketing/mar012-policy-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    }, {
                        Name: "Quản lý tag",
                        Actived: false,
                        Code: "mar016-hashtag-list",
                        Link: "/marketing/mar016-hashtag-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết tag",
                            Actived: false,
                            Code: "mar016-hashtag-detail",
                            Link: "/marketing/mar016-hashtag-detail",
                            Type: 'function',
                            LstChild: [],
                        }],
                    }, {
                        Name: "Phân nhóm Web",
                        Actived: false,
                        Code: "mar017-category-web",
                        Link: "/marketing/mar017-category-web",
                        Type: 'function',
                        LstChild: [],
                    }, {
                        Name: "Thẻ meta",
                        Actived: false,
                        Code: "mar018-metatag",
                        Link: "/marketing/mar018-metatag",
                        Type: 'function',
                        LstChild: [],
                    }, {
                        Name: "Từ khóa đề nghị",
                        Actived: false,
                        Code: "mar018-search-keyword",
                        Link: "/marketing/mar018-search-keyword",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Cấu hình web",
                        Actived: false,
                        Code: "mar020-config",
                        Link: "/marketing/mar020-config",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "SEO",
                        Actived: false,
                        Code: "mar020-seo",
                        Link: "/marketing/mar020-seo",
                        Type: 'function',
                        LstChild: [],
                    },
                ],
            },
            {
                Name: "Giới thiệu",
                Actived: false,
                Code: "mar-intro",
                Link: "/marketing/mar013-introduce-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Giới thiệu chung",
                        Actived: false,
                        Code: "mar013-introduce-list",
                        Link: "/marketing/mar013-introduce-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết phần giới thiệu",
                            Actived: false,
                            Code: "mar013-introduce-detail",
                            Link: "/marketing/mar013-introduce-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Hệ thống cửa hàng",
                        Actived: false,
                        Code: "mar014-store-system-list",
                        Link: "/marketing/mar014-store-system-list",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Câu hỏi thường gặp",
                        Actived: false,
                        Code: "mar015-common-questions-list",
                        Link: "/marketing/mar015-common-questions-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "CHỈNH SỬA CÂU TRẢ LỜI",
                            Actived: false,
                            Code: "mar015-common-questions-detail",
                            Link: "/marketing/mar015-common-questions-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    }
                ]
            },
            {
                Name: "DS báo cáo Excel",
                Actived: false,
                Code: "mar-report",
                Link: "/marketing/mar001-report",
                Type: 'function',
                LstChild: [
                    {
                        Name: "DS báo cáo Excel",
                        Actived: false,
                        Code: "mar001-report",
                        Link: "/marketing/mar001-report",
                        Type: 'function',
                        LstChild: [],
                    }
                ],
            },
            {
                Name: "Chính sách",
                Actived: false,
                Code: "policy",
                Link: "/marketing/mar004-coupon-list",
                Type: 'group',
                LstChild: [{
                    Name: "Coupon",
                    Actived: false,
                    Code: "mar004-coupon-list",
                    Link: "/marketing/mar004-coupon-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Đợt phát hành",
                        Actived: false,
                        Code: "mar004-coupon-detail",
                        Link: "/marketing/mar004-coupon-detail",
                        Type: '',
                        LstChild: [],
                    }],
                }, {
                    Name: "Phân nhóm PMH/Coupon",
                    Actived: false,
                    Code: "mar005-coupon-group",
                    Link: "/marketing/mar005-coupon-group",
                    Type: 'function',
                    LstChild: [],
                }, {
                    Name: "Best Price",
                    Actived: false,
                    Code: "mar006-bestprice-list",
                    Link: "/marketing/mar006-bestprice-list",
                    Type: 'function',
                    LstChild: [],
                }, {
                    Name: "Hàng độc đáo",
                    Actived: false,
                    Code: "mar007-special-product-list",
                    Link: "/marketing/mar007-special-product-list",
                    Type: 'function',
                    LstChild: [],
                }, {
                    Name: "Chủ đề nổi bật",
                    Actived: false,
                    Code: "mar008-album-list",
                    Link: "/marketing/mar008-album-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Chủ đề nổi bật",
                        Actived: false,
                        Code: "mar008-album-detail",
                        Link: "/marketing/mar008-album-detail",
                        Type: '',
                        LstChild: [],
                    }],
                },
                {
                    Name: "Import Excel",
                    Actived: false,
                    Code: "mar001-report-import",
                    Link: "/marketing/mar001-report-import",
                    Type: 'function',
                    LstChild: [],
                },],
            },
            {
                Name: "Báo cáo",
                Actived: false,
                Code: "mar-report",
                Link: "/marketing/mar001-report",
                Type: 'group',
                LstChild: [
                    {
                        Name: "DS báo cáo Excel",
                        Actived: false,
                        Code: "mar001-report",
                        Link: "/marketing/mar001-report",
                        Type: 'function',
                        LstChild: [],
                    },],
            },
        ]
    },
    //HRI
    {
        Code: 'hri',
        Name: 'Nhân sự',
        Actived: true,
        Link: '/hri/hri040-dashboard',
        Path: 'hri',
        LoadChildren: () => import('../../p-hri/p-hri.module').then(m => m.PHriModule),
        ListMenu: [
            {
                Name: "Dashboard",
                Actived: false,
                Code: "hri040-dashboard",
                Link: "/hri/hri040-dashboard",
                Type: 'function',
                LstChild: [],
            },
            {
                Name: "Cơ cấu tổ chức",
                Actived: false,
                Code: "hriOrg",
                Link: "/hri/hri006-department-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Cơ cấu tổ chức",
                        Actived: false,
                        Code: "hri006-department-list",
                        Link: "/hri/hri006-department-list",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Điểm làm việc",
                        Actived: false,
                        Code: "hri005-location-list",
                        Link: "/hri/hri005-location-list",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Định biên nhân sự",
                        Actived: false,
                        Code: "hri041-manpower-list",
                        Link: "/hri/hri041-manpower-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết định biên nhân sự",
                            Actived: false,
                            Code: "hri041-manpower-detail",
                            Link: "/hri/hri041-manpower-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    }
                ],
            },
            {
                Name: "Hồ sơ nhân sự",
                Actived: false,
                Code: "hriStaff",
                Link: "/hri/hr001-staff-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Danh sách nhân sự",
                        Actived: false,
                        Code: "hr001-staff-list",
                        Link: "/hri/hr001-staff-list",
                        Type: 'function',
                        LstChild: [
                            {
                                Name: "Hồ sơ nhân sự",
                                Actived: false,
                                Code: "hr001-staff-detail",
                                Link: "/hri/hr001-staff-detail",
                                Type: '',
                                LstChild: [],
                            },
                            {
                                Name: "Chính sách",
                                Actived: false,
                                Code: "",
                                Link: "",
                                Type: '',
                                LstChild: [],
                            },
                            {
                                Name: "BHNN & thuế TNCN",
                                Actived: false,
                                Code: "",
                                Link: "",
                                Type: '',
                                LstChild: [],
                            },
                            {
                                Name: "Đào tạo",
                                Actived: false,
                                Code: "",
                                Link: "",
                                Type: '',
                                LstChild: [],
                            },
                            {
                                Name: "Dữ liệu công tác",
                                Actived: false,
                                Code: "hri039-employee-activity-log",
                                Link: "/hri/hri039-employee-activity-log",
                                Type: '',
                                LstChild: [],
                            },
                            {
                                Name: "Thông tin cá nhân",
                                Actived: false,
                                Code: "hr007-personal-info",
                                Link: "/hri/hr007-personal-info",
                                Type: '',
                                LstChild: [],
                            }
                        ],
                    },
                ],
            },
            {
                Name: "Đánh giá nhân sự",
                Actived: false,
                Code: "hriCompetency",
                Link: "/hri/hr007-competency-bank",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Từ điển năng lực",
                        Actived: false,
                        Code: "hr007-competency-bank",
                        Link: "/hri/hr007-competency-bank",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Khung năng lực",
                        Actived: false,
                        Code: "hri013-competency-framework",
                        Link: "/hri/hri013-competency-framework",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Khung năng lực",
                            Actived: false,
                            Code: "hri013-competency-framework-detail",
                            Link: "/hri/hri013-competency-framework-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Phân nhóm câu hỏi",
                        Actived: false,
                        Code: "hr009-question-group",
                        Link: "/hri/hr009-question-group",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Ngân hàng câu hỏi",
                        Actived: false,
                        Code: "hri008-question-bank-list",
                        Link: "/hri/hri008-question-bank-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Câu hỏi",
                            Actived: false,
                            Code: "hri008-question-bank-detail",
                            Link: "/hri/hri008-question-bank-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Quản lý Đợt đánh giá",
                        Actived: false,
                        Code: "hri010-evaluation-tranche",
                        Link: "/hri/hri010-evaluation-tranche",
                        Type: 'function',
                        LstChild: [{
                            Name: "Thiết lập Đợt đánh giá",
                            Actived: false,
                            Code: "hri010-evaluation-tranche-detail",
                            Link: "/hri/hri010-evaluation-tranche-detail",
                            Type: '',
                            LstChild: [],
                        },
                        {
                            Name: "Giám sát Đợt đánh giá",
                            Actived: false,
                            Code: "hri011-quiz-monitor",
                            Link: "/hri/hri011-quiz-monitor",
                            Type: 'function',
                            LstChild: [
                                {
                                    Name: "Xem bài làm",
                                    Actived: false,
                                    Code: "hri014-exam-monitor",
                                    Link: "/hri/hri014-exam-monitor",
                                    Type: 'function',
                                    LstChild: [],
                                },
                            ],
                        },
                        {
                            Name: "Chấm bài tự luận",
                            Actived: false,
                            Code: "hri012-quiz-marking",
                            Link: "/hri/hri012-quiz-marking",
                            Type: 'function',
                            LstChild: [],
                        },
                        {
                            Name: "Yêu cầu phúc khảo",
                            Actived: false,
                            Code: "hri016-appeal-list",
                            Link: "/hri/hri016-appeal-list",
                            Type: 'function',
                            LstChild: [
                                {
                                    Name: "Chấm câu hỏi phúc khảo",
                                    Actived: false,
                                    Code: "hri017-re-evaluate",
                                    Link: "/hri/hri017-re-evaluate",
                                    Type: '',
                                    LstChild: [],
                                },
                                {
                                    Name: "Xem y/c phúc khảo",
                                    Actived: false,
                                    Code: "hri018-exam-appeal",
                                    Link: "/hri/hri018-exam-appeal",
                                    Type: 'function',
                                    LstChild: [],
                                },
                            ],
                        }],
                    },
                ],
            },
            {
                Name: "Chính sách",
                Actived: false,
                Code: "hriPolicy",
                Link: "/hri/hri020-news-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Bài viết",
                        Actived: false,
                        Code: "hri020-news-list",
                        Link: "/hri/hri020-news-list",
                        Type: 'function',
                        LstChild: [
                            {
                                Name: "Chi tiết bài viết",
                                Actived: false,
                                Code: "hri020-news-detail",
                                Link: "/hri/hri020-news-detail",
                                Type: 'function',
                                LstChild: [],
                            },
                        ],
                    },
                    {
                        Name: "Onboarding",
                        Actived: false,
                        Code: "hri021-policy-onboarding-list",
                        Link: "/hri/hri021-policy-onboarding-list",
                        Type: 'function',
                        LstChild: [
                            {
                                Name: "Chi tiết bảng c.việc Onboarding",
                                Actived: false,
                                Code: "hri021-policy-onboarding-detail",
                                Link: "/hri/hri021-policy-onboarding-detail",
                                Type: 'function',
                                LstChild: [],
                            },
                        ],
                    },
                    {
                        Name: "Offboarding",
                        Actived: false,
                        Code: "hri022-policy-offboarding-list",
                        Link: "/hri/hri022-policy-offboarding-list",
                        Type: 'function',
                        LstChild: [
                            {
                                Name: "Chi tiết bảng c.việc Offboarding",
                                Actived: false,
                                Code: "hri022-policy-offboarding-detail",
                                Link: "/hri/hri022-policy-offboarding-detail",
                                Type: 'function',
                                LstChild: [],
                            },
                        ],
                    },
                    {
                        Name: "TaskCategory",
                        Actived: false,
                        Code: "hri042-task-category-list",
                        Link: "/hri/hri042-task-category-list",
                        Type: 'function',
                        LstChild: [
                            {
                                Name: "Danh mục đầu việc",
                                Actived: false,
                                Code: "hri042-task-category-list",
                                Link: "/hri/hri042-task-category-list",
                                Type: 'function',
                                LstChild: [],
                            },
                        ],
                    },
                ],
            },
            {
                Name: "Tiền lương",
                Actived: false,
                Code: "hriSal",//"hri002-policysalary",
                Link: "/hri/hri002-policysalary",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Bảng lương",
                        Actived: false,
                        Code: "hri019-payroll-list",
                        Link: "/hri/hri019-payroll-list",
                        Type: 'function',
                        LstChild: [
                            {
                                Name: "Chi tiết bảng lương",
                                Actived: false,
                                Code: "hri019-payroll-detail",
                                Link: "/hri/hri019-payroll-detail",
                                Type: '',
                                LstChild: [
                                    {
                                        Name: "Phiếu lương",
                                        Actived: false,
                                        Code: "hri019-paycheck-detail",
                                        Link: "/hri/hri019-paycheck-detail",
                                        Type: '',
                                        LstChild: [],
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        Name: "Phụ cấp",
                        Actived: false,
                        Code: "hri003-policyallowance",
                        Link: "/hri/hri003-policyallowance",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Thưởng",
                        Actived: false,
                        Code: "hri004-policyreward",
                        Link: "/hri/hri004-policyreward",
                        Type: 'function',
                        LstChild: [],
                    },
                ],
            },
            {
                Name: "Quyết định",
                Actived: false,
                Code: "hriDecision",
                Link: "/hri/hri023-decision-hiring-list",
                Type: 'group',
                LstChild: [{
                    Name: "Quyết định tuyển dụng",
                    Actived: false,
                    Code: "hri023-decision-hiring-list",
                    Link: "/hri/hri023-decision-hiring-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết quyết định tuyển dụng",
                        Actived: false,
                        Code: "hri023-decision-hiring-detail",
                        Link: "/hri/hri023-decision-hiring-detail",
                        Type: '',
                        LstChild: [],
                    },],
                },
                {
                    Name: "Quyết định xin nghỉ việc",
                    Actived: false,
                    Code: "hri026-resignation-decision-list",
                    Link: "/hri/hri026-resignation-decision-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết quyết định xin nghỉ việc",
                        Actived: false,
                        Code: "hri026-resignation-decision-detail",
                        Link: "/hri/hri026-resignation-decision-detail",
                        Type: '',
                        LstChild: [],
                    },],
                },
                {
                    Name: "Quyết định điều chuyển",
                    Actived: false,
                    Code: "hri024-transfer-decision-list",
                    Link: "/hri/hri024-transfer-decision-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết quyết định điều chuyển",
                        Actived: false,
                        Code: "hri024-transfer-decision-detail",
                        Link: "/hri/hri024-transfer-decision-detail",
                        Type: '',
                        LstChild: [],
                    },],
                },
                    // {
                    //     Name: "Quyết định kỷ luật",
                    //     Actived: false,
                    //     Code: "hri027-termination-decision-list",
                    //     Link: "/hri/hri027-termination-decision-list",
                    //     Type: 'function',
                    //     LstChild: [{
                    //         Name: "Chi tiết quyết định kỷ luật",
                    //         Actived: false,
                    //         Code: "hri027-termination-decision-detail",
                    //         Link: "/hri/hri027-termination-decision-detail",
                    //         Type: '',
                    //         LstChild: [],
                    //     },],
                    // },
                ],
            },
            {
                Name: "Onboard",
                Actived: false,
                Code: "hriOnboard",
                Link: "/hri/hri028-pre-onboarding-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Chuẩn bị Onboarding",
                        Actived: false,
                        Code: "hri028-pre-onboarding-list",
                        Link: "/hri/hri028-pre-onboarding-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết chuẩn bị Onboarding",
                            Actived: false,
                            Code: "hri028-pre-onboarding-detail",
                            Link: "/hri/hri028-pre-onboarding-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Onboarding",
                        Actived: false,
                        Code: "hri029-onboarding-list",
                        Link: "/hri/hri029-onboarding-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Onboarding",
                            Actived: false,
                            Code: "hri029-onboarding-detail",
                            Link: "/hri/hri029-onboarding-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Onboarded",
                        Actived: false,
                        Code: "hri030-onboarded-list",
                        Link: "/hri/hri030-onboarded-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Onboarded",
                            Actived: false,
                            Code: "hri030-onboarded-detail",
                            Link: "/hri/hri030-onboarded-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Ngưng Onboarding",
                        Actived: false,
                        Code: "hri031-stop-onboarding-list",
                        Link: "/hri/hri031-stop-onboarding-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết ngưng onboarding",
                            Actived: false,
                            Code: "hri031-stop-onboarding-detail",
                            Link: "/hri/hri031-stop-onboarding-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                ],
            },
            {
                Name: "Offboard",
                Actived: false,
                Code: "hriOffboard",
                Link: "/hri/hri032-pre-offboarding-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Chuẩn bị Offboarding",
                        Actived: false,
                        Code: "hri032-pre-offboarding-list",
                        Link: "/hri/hri032-pre-offboarding-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết chuẩn bị Offboarding",
                            Actived: false,
                            Code: "hri032-pre-offboarding-detail",
                            Link: "/hri/hri032-pre-offboarding-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Offboarding",
                        Actived: false,
                        Code: "hri033-offboarding-list",
                        Link: "/hri/hri033-offboarding-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Offboarding",
                            Actived: false,
                            Code: "hri033-offboarding-detail",
                            Link: "/hri/hri033-offboarding-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Offboarded",
                        Actived: false,
                        Code: "hri034-offboarded-list",
                        Link: "/hri/hri034-offboarded-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Offboarded",
                            Actived: false,
                            Code: "hri034-offboarded-detail",
                            Link: "/hri/hri034-offboarded-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Ngưng Offboarding",
                        Actived: false,
                        Code: "hri035-stop-offboarding-list",
                        Link: "/hri/hri035-stop-offboarding-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết ngưng Offboarding",
                            Actived: false,
                            Code: "hri035-stop-offboarding-detail",
                            Link: "/hri/hri035-stop-offboarding-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                ],
            },
            {
                Name: "Xử lý kỷ luật",
                Actived: false,
                Code: "hriDisciplinary",
                Link: "/hri/hri036-disciplinary-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Bảng c.việc XLKL",
                        Actived: false,
                        Code: "hri036-disciplinary-list",
                        Link: "/hri/hri036-disciplinary-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết bảng c.việc XLKL",
                            Actived: false,
                            Code: "hri036-disciplinary-detail",
                            Link: "/hri/hri036-disciplinary-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Yêu cầu kỷ luật",
                        Actived: false,
                        Code: "hri037-disciplinary-requirement-list",
                        Link: "/hri/hri037-disciplinary-requirement-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Yêu cầu kỷ luật",
                            Actived: false,
                            Code: "hri037-disciplinary-requirement-detail",
                            Link: "/hri/hri037-disciplinary-requirement-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                    {
                        Name: "Quyết đinh kỷ luật",
                        Actived: false,
                        Code: "hri038-disciplinary-decision-list",
                        Link: "/hri/hri038-disciplinary-decision-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Quyết đinh kỷ luật",
                            Actived: false,
                            Code: "hri038-disciplinary-decision-detail",
                            Link: "/hri/hri038-disciplinary-decision-detail",
                            Type: '',
                            LstChild: [],
                        },],
                    },
                ],
            },
            {
                Name: "Đề xuất",
                Actived: false,
                Code: "hriRequest",
                Link: "/hri/hri025-resignation-request-list",
                Type: 'group',
                LstChild: [{
                    Name: "Đơn xin nghỉ việc",
                    Actived: false,
                    Code: "hri025-resignation-request-list",
                    Link: "/hri/hri025-resignation-request-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết đơn xin nghỉ việc",
                        Actived: false,
                        Code: "hri025-resignation-request-detail",
                        Link: "/hri/hri025-resignation-request-detail",
                        Type: '',
                        LstChild: [],
                    },],
                },],
            },
            {
                Name: "Báo cáo",
                Actived: false,
                Code: "hriReport",
                Link: "/hri/hri015-exam-report",
                Type: 'group',
                LstChild: [{
                    Name: "Báo cáo đánh giá",
                    Actived: false,
                    Code: "hri015-exam-report",
                    Link: "/hri/hri015-exam-report",
                    Type: 'function',
                    LstChild: [{
                        Name: "Báo cáo chi tiết kết quả kiểm tra",
                        Actived: false,
                        Code: "hri015-exam-report-detail",
                        Link: "/hri/hri015-exam-report-detail",
                        Type: '',
                        LstChild: [],
                    }, {
                        Name: "Báo cáo phân tích câu hỏi",
                        Actived: false,
                        Code: "hri015-analysis-report-question",
                        Link: "/hri/hri015-analysis-report-question",
                        Type: '',
                        LstChild: [],
                    }, {
                        Name: "Báo cáo câu hỏi sai và đáp án đúng",
                        Actived: false,
                        Code: "hri015-wrong-report-question",
                        Link: "/hri/hri015-wrong-report-question",
                        Type: '',
                        LstChild: [],
                    }],
                },],
            }
        ]
    },
    //ECOM
    {
        Code: 'ecommerce',
        Name: 'ecommerce',
        Actived: true,
        Link: 'ecommerce/ecom001-online-order',
        Path: 'ecommerce',
        LoadChildren: () => import('../../p-ecommerce/p-ecommerce.module').then(m => m.PEcommerceModule),
        ListMenu: [
            {
                Name: "Dashboard",
                Actived: false,
                Code: "ecom013-dashboard",
                Link: "/ecommerce/ecom013-dashboard",
                Type: 'function',
                LstChild: [],
            },
            {
                Name: "Thương hiệu",
                Actived: false,
                Code: "ecom002-brandlist",
                Link: "/ecommerce/ecom002-brandlist",
                Type: 'function',
                LstChild: [],
            },
            {
                Name: "Các điểm thuộc công ty",
                Actived: false,
                Code: "ecom002-locationlist",
                Link: "/ecommerce/ecom002-locationlist",
                Type: 'function',
                LstChild: [],
            },
            {
                Name: "Vận hành",
                Actived: false,
                Code: "ecom-op",
                Link: "/ecommerce/ecom007-inport-list",
                Type: 'group',
                LstChild: [{
                    Name: "Nhập điều chuyển",
                    Actived: false,
                    Code: "ecom007-inport-list",
                    Link: "/ecommerce/ecom007-inport-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Nhập điều chuyển",
                        Actived: false,
                        Code: "ecom007-inport-detail",
                        Link: "/ecommerce/ecom007-inport-detail",
                        Type: '',
                        LstChild: [],
                    }],
                }, {
                    Name: "Xuất điều chuyển",
                    Actived: false,
                    Code: "ecom008-outport-list",
                    Link: "/ecommerce/ecom008-outport-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Xuất điều chuyển",
                        Actived: false,
                        Code: "ecom008-outport-detail",
                        Link: "/ecommerce/ecom008-outport-detail",
                        Type: '',
                        LstChild: [],
                    }],
                }],
            },
            {
                Name: "Giỏ hàng",
                Actived: false,
                Code: "ecom-cart",
                Link: "/ecommerce/ecom009-cart-customer-list",
                Type: 'group',
                LstChild: [{
                    Name: "Giỏ hàng khách",
                    Actived: false,
                    Code: "ecom009-cart-customer-list",
                    Link: "/ecommerce/ecom009-cart-customer-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Giỏ hàng của khách",
                        Actived: false,
                        Code: "ecom009-cart-customer-detail",
                        Link: "/ecommerce/ecom009-cart-customer-detail",
                        Type: '',
                        LstChild: [],
                    }],
                }, {
                    Name: "Giỏ hàng tự tạo",
                    Actived: false,
                    Code: "ecom010-cart-generate-list",
                    Link: "/ecommerce/ecom010-cart-generate-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Giỏ hàng tự tạo",
                        Actived: false,
                        Code: "ecom010-cart-generate-detail",
                        Link: "/ecommerce/ecom010-cart-generate-detail",
                        Type: '',
                        LstChild: [],
                    }],
                }],
            },
            {
                Name: "Đơn hàng",
                Actived: false,
                Code: "ecom-order",
                Link: "/ecommerce/ecom001-online-order",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Master Online",
                        Actived: false,
                        Code: "ecom002-online-master",
                        Link: "/ecommerce/ecom002-online-master",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Đơn hàng Online",
                        Actived: false,
                        Code: "ecom001-online-order",
                        Link: "/ecommerce/ecom001-online-order",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Đơn hàng",
                            Actived: false,
                            Code: "ecom001-online-order-detail",
                            Link: "/ecommerce/ecom001-online-order-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Đơn hàng Điều phối",
                        Actived: false,
                        Code: "ecom001-online-order-lgt",
                        Link: "/ecommerce/ecom001-online-order-lgt",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Đơn hàng Điều phối",
                            Actived: false,
                            Code: "ecom001-online-order-lgt-detail",
                            Link: "/ecommerce/ecom001-online-order-lgt-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Import Excel",
                        Actived: false,
                        Code: "ecom001-report-import",
                        Link: "/ecommerce/ecom001-report-import",
                        Type: 'function',
                        LstChild: [],
                    },],
            },
            {
                Name: "Kênh bán hàng",
                Actived: false,
                Code: "ecom-channel",
                Link: "/ecommerce/ecom003-channel-list",
                Type: 'group',
                LstChild: [{
                    Name: "Kênh bán hàng",
                    Actived: false,
                    Code: "ecom003-channel-list",
                    Link: "/ecommerce/ecom003-channel-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Sản phẩm onsite",
                        Actived: false,
                        Code: "ecom006-product-onsite-list",
                        Link: "/ecommerce/ecom006-product-onsite-list",
                        Type: '',
                        LstChild: [],
                    },]
                },
                {
                    Name: "Nhóm kênh bán hàng",
                    Actived: false,
                    Code: "ecom011-channel-group",
                    Link: "/ecommerce/ecom011-channel-group",
                    Type: 'function',
                    LstChild: []
                },
                {
                    Name: "Sản phẩm",
                    Actived: false,
                    Code: "ecom012-product-channel",
                    Link: "/ecommerce/ecom012-product-channel",
                    Type: 'function',
                    LstChild: []
                },
                {
                    Name: "Kế hoạch phân bổ hàng",
                    Actived: false,
                    Code: "ecom014-product-forecast",
                    Link: "/ecommerce/ecom014-product-forecast",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Kế hoạch phân bổ hàng",
                        Actived: false,
                        Code: "ecom014-product-forecast-detail",
                        Link: "/ecommerce/ecom014-product-forecast-detail",
                        Type: '',
                        LstChild: [],
                    }]
                },
                {
                    Name: "Giới hạn tồn sản phẩm",
                    Actived: false,
                    Code: "ecom015-stock-limit",
                    Link: "/ecommerce/ecom015-stock-limit",
                    Type: 'function',
                    LstChild: []
                },
                {
                    Name: "Điều chuyển hàng hóa",
                    Actived: false,
                    Code: "ecom016-product-transfer",
                    Link: "/ecommerce/ecom016-product-transfer",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Điều chuyển hàng hóa",
                        Actived: false,
                        Code: "ecom016-product-transfer-detail",
                        Link: "/ecommerce/ecom016-product-transfer-detail",
                        Type: '',
                        LstChild: [],
                    }]
                },]
            },
            {
                Name: "Chính sách",
                Actived: false,
                Code: "ecom-policy",
                Link: "/ecommerce/ecom005-dead-link",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Dead Link",
                        Actived: false,
                        Code: "ecom005-dead-link",
                        Link: "/ecommerce/ecom005-dead-link",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Back Link",
                        Actived: false,
                        Code: "ecom005-back-link",
                        Link: "/ecommerce/ecom005-back-link",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Short Link",
                        Actived: false,
                        Code: "ecom005-short-link",
                        Link: "/ecommerce/ecom005-short-link",
                        Type: 'function',
                        LstChild: [],
                    }
                ]
            },
            {
                Name: "Báo cáo",
                Actived: false,
                Code: "ecom-report",
                Link: "/ecommerce/ecom004-report",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Báo cáo Excel",
                        Actived: false,
                        Code: "ecom004-report",
                        Link: "/ecommerce/ecom004-report",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Bài viết",
                        Actived: false,
                        Code: "ecom002-news",
                        Link: "/ecommerce/ecom002-news",
                        Type: 'function',
                        LstChild: [],
                    },],
            },
        ]
    },
    //PUR
    {
        Code: 'pur',
        Name: 'Mua hàng',
        Actived: true,
        Link: 'pur/pur008-price-request-list',
        Path: 'pur',
        LoadChildren: () => import('../../p-purchase/p-purchase.module').then(m => m.PPurchaseModule),
        ListMenu: [
            // {
            //     Name: "Dashboard",
            //     Actived: false,
            //     Code: "pur010-dashboard",
            //     Link: "/pur/pur002-brand-list",
            //     Type: 'function',
            //     LstChild: [],
            // },
            {
                Name: "Mua hàng",
                Actived: false,
                Code: "pur-po",
                Link: "/pur/pur008-price-request-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Cập nhật báo giá",
                        Actived: false,
                        Code: "pur008-price-request-list",
                        Link: "/pur/pur008-price-request-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Cập nhật báo giá",
                            Actived: false,
                            Code: "pur008-price-request-detail",
                            Link: "/pur/pur008-price-request-detail",
                            Type: '',
                            LstChild: [
                                {
                                    Name: "Chi tiết Sản phẩm báo giá",
                                    Actived: false,
                                    Code: "pur008-price-product-detail",
                                    Link: "/pur/pur008-price-product-detail",
                                    Type: '',
                                }
                            ],
                        }],
                    },
                    {
                        Name: "PO nội địa",
                        Actived: false,
                        Code: "pur003-po-domestic",
                        Link: "/pur/pur003-po-domestic",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết PO nội địa",
                            Actived: false,
                            Code: "pur003-po-domestic-detail",
                            Link: "/pur/pur003-po-domestic-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    // {//tính năng dư, có thể sau này dùng cho UI khác
                    //     Name: "PO nhà cung cấp",
                    //     Actived: false,
                    //     Code: "pur004-po-supplier",
                    //     Link: "/pur/pur004-po-supplier",
                    //     Type: 'function',
                    //     LstChild: [{
                    //         Name: "Chi tiết PO nhà cung cấp",
                    //         Actived: false,
                    //         Code: "pur004-po-supplier-detail",
                    //         Link: "/pur/pur004-po-supplier-detail",
                    //         Type: '',
                    //         LstChild: [],
                    //     }],
                    // }
                ]
            },
            {
                Name: "Listing Sản phẩm",
                Actived: false,
                Code: "pur-propose",
                Link: "/pur/config007-cargo-status",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Tình trạng hàng hóa",
                        Actived: false,
                        Code: "config007-cargo-status",
                        Link: "/pur/config007-cargo-status",
                        Type: 'function',
                        LstChild: []
                    },
                    {
                        Name: "Phân nhóm khai quan",
                        Actived: false,
                        Code: "config010-tax-group",
                        Link: "/pur/config010-tax-group",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Quản lý khai quan",
                        Actived: false,
                        Code: "config009-tax-list",
                        Link: "/pur/config009-tax-list",
                        Type: 'function',
                        LstChild: [],
                    },
                    {
                        Name: "Đề xuất hàng mới",
                        Actived: false,
                        Code: "pur010-proposed-new-product-list",
                        Link: "/pur/pur010-proposed-new-product-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Thông tin chi tiết đề xuất",
                            Actived: false,
                            Code: "pur010-proposed-new-product-detail",
                            Link: "/pur/pur010-proposed-new-product-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Đề xuất quà tặng",
                        Actived: false,
                        Code: "pur011-product-gift-list",
                        Link: "/pur/pur011-product-gift-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Thông tin chi tiết đề xuất quà tặng",
                            Actived: false,
                            Code: "pur011-product-gift-detail",
                            Link: "/pur/pur011-product-gift-detail",
                            Type: '',
                            LstChild: [],
                        }],
                    },
                    {
                        Name: "Đề nghị Hamper",
                        Actived: false,
                        Code: "config002-hamper-request",
                        Link: "/pur/config002-hamper-request",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết hamper",
                            Actived: false,
                            Code: "config002-hamper-request-detail",
                            Link: "/pur/config002-hamper-request-detail",
                            Type: '',
                            LstChild: [],
                        }]
                    },
                ]
            },
            {
                Name: "Chính sách",
                Actived: false,
                Code: "pur-policy",
                Link: "/pur/pur002-brand-list",
                Type: 'group',
                LstChild: [{
                    Name: "Thương hiệu sản phẩm",
                    Actived: false,
                    Code: "pur002-brand-list",
                    Link: "/pur/pur002-brand-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Thương hiệu sản phẩm",
                        Actived: false,
                        Code: "pur002-brand-detail",
                        Link: "/pur/pur002-brand-detail",
                        Type: '',
                        LstChild: [],
                    }],
                },
                {
                    Name: "NCC nội địa",
                    Actived: false,
                    Code: "pur005-supplier-list",
                    Link: "/pur/pur005-supplier-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết nhà cung cấp",
                        Actived: false,
                        Code: "pur005-supplier-detail",
                        Link: "/pur/pur005-supplier-detail",
                        Type: '',
                        LstChild: [],
                    }, {
                        Name: "Người liên hệ",
                        Actived: false,
                        Code: "pur006-partner-contact",
                        Link: "/pur/pur006-partner-contact",
                        Type: '',
                        LstChild: [],
                    }, {
                        Name: "Sản phẩm đặt mua",
                        Actived: false,
                        Code: "pur007-partner-product",
                        Link: "/pur/pur007-partner-product",
                        Type: '',
                        LstChild: [],
                    }, {
                        Name: "ĐK thương mại",
                        Actived: false,
                        Code: "",
                        Link: "",
                        Type: '',
                        LstChild: [],
                    }, {
                        Name: "Lịch sử mua hàng",
                        Actived: false,
                        Code: "",
                        Link: "",
                        Type: '',
                        LstChild: [],
                    }, {
                        Name: "Chứng từ liên quan",
                        Actived: false,
                        Code: "",
                        Link: "",
                        Type: '',
                        LstChild: [],
                    }, {
                        Name: "Template email",
                        Actived: false,
                        Code: "pur009-partner-template-email",
                        Link: "/pur/pur009-partner-template-email",
                        Type: '',
                        LstChild: [],
                    }],
                },
                {
                    Name: "Import Excel",
                    Actived: false,
                    Code: "pur001-report-import",
                    Link: "/pur/pur001-report-import",
                    Type: 'function',
                    LstChild: [],
                },]
            },
            {
                Name: "Báo cáo",
                Actived: false,
                Code: "pur-report",
                Link: "/pur/pur001-report",
                Type: 'group',
                LstChild: [
                    {
                        Name: "DS báo cáo Excel",
                        Actived: false,
                        Code: "pur001-report",
                        Link: "/pur/pur001-report",
                        Type: 'function',
                        LstChild: [],
                    },]
            },
        ]
    },
    //CONFIG
    {
        Code: 'config',
        Name: 'CẤU HÌNH',
        Actived: true,
        Link: 'config/config001-product-list',
        Path: 'config',
        LoadChildren: () => import('../../p-config/p-config.module').then(m => m.PConfigModule),
        ListMenu: [
            // {
            //     Name: "Dashboard",
            //     Actived: false,
            //     Code: "config007-dashboard",
            //     Link: "config/config001-product-list",
            //     Type: 'function',
            //     LstChild: [],
            // },
            {
                Name: "Sản phẩm",
                Actived: false,
                Code: "erpproduct",
                Link: "/config/config001-product-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "DS Sản phẩm",
                        Actived: false,
                        Code: "config001-product-list",
                        Link: "/config/config001-product-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Sản phẩm",
                            Actived: false,
                            Code: "config001-product-detail",
                            Link: "/config/config001-product-detail",
                            Type: 'function',
                            LstChild: [{
                                Name: "Chi tiết Hamper",
                                Actived: false,
                                Code: "config002-hamper-detail-request",
                                Link: "/config/config002-hamper-detail-request",
                                Type: '',
                                LstChild: [],
                            },],
                        },]
                    },
                    {
                        Name: "DS Hamper",
                        Actived: false,
                        Code: "config002-hamper-list",
                        Link: "/config/config002-hamper-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Hamper",
                            Actived: false,
                            Code: "config002-hamper-detail",
                            Link: "/config/config002-hamper-detail",
                            Type: 'function',
                            LstChild: [
                                {
                                    Name: "Chi tiết Hamper",
                                    Actived: false,
                                    Code: "config002-hamper-detail-request",
                                    Link: "/config/config002-hamper-detail-request",
                                    Type: '',
                                    LstChild: [],
                                },
                            ],
                        },]
                    },
                    {
                        Name: "DS Quà tặng",
                        Actived: false,
                        Code: "config001-gift-list",
                        Link: "/config/config001-gift-list",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Sản phẩm",
                            Actived: false,
                            Code: "config001-gift-detail",
                            Link: "/config/config001-gift-detail",
                            Type: 'function',
                            LstChild: [],
                        },]
                    },
                ],
            },
            // {
            //     Name: "hàng hóa",
            //     Actived: false,
            //     Code: "erpmerchandise",
            //     Link: "/config/config007-cargo-status",
            //     Type: 'group',
            //     LstChild: [
            //         {
            //             Name: "Tình trạng hàng hóa",
            //             Actived: false,
            //             Code: "config007-cargo-status",
            //             Link: "/config/config007-cargo-status",
            //             Type: 'function',
            //             LstChild: []
            //         },
            //     ]
            // }, 
            {
                Name: "Quản lý sản phẩm",
                Actived: false,
                Code: "product",
                Link: "/config/config003-enterprise-product",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Danh sách Sản phẩm",
                        Actived: false,
                        Code: "config003-enterprise-product",
                        Link: "/config/config003-enterprise-product",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Sản phẩm",
                            Actived: false,
                            Code: "config003-enterprise-product-detail",
                            Link: "/config/config003-enterprise-product-detail",
                            Type: 'function',
                            LstChild: [],
                        }]
                    },
                    {
                        Name: "Danh sách Hamper",
                        Actived: false,
                        Code: "config003-enterprise-hamper",
                        Link: "/config/config003-enterprise-hamper",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Hamper",
                            Actived: false,
                            Code: "config003-enterprise-product-detail",
                            Link: "/config/config003-enterprise-product-detail",
                            Type: 'function',
                            LstChild: [],
                        }]
                    },
                    {
                        Name: "Danh sách Quà tặng",
                        Actived: false,
                        Code: "config003-enterprise-gift",
                        Link: "/config/config003-enterprise-gift",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết Quà tặng",
                            Actived: false,
                            Code: "config003-enterprise-product-detail",
                            Link: "/config/config003-enterprise-product-detail",
                            Type: 'function',
                            LstChild: [],
                        }]
                    },
                    {
                        Name: "Đề nghị Hamper",
                        Actived: false,
                        Code: "config002-hamper-request",
                        Link: "/config/config002-hamper-request",
                        Type: 'function',
                        LstChild: [{
                            Name: "Chi tiết hamper",
                            Actived: false,
                            Code: "config002-hamper-request-detail",
                            Link: "/config/config002-hamper-request-detail",
                            Type: '',
                            LstChild: [],
                        }]
                    }],
            }, {
                Name: "Hồ sơ nhân sự",
                Actived: false,
                Code: "personal",
                Link: "/config/config008-enterprise-personal-info-list",
                Type: 'group',
                LstChild: [{
                    Name: "Thông tin cá nhân",
                    Actived: false,
                    Code: "config008-enterprise-personal-info-list",
                    Link: "/config/config008-enterprise-personal-info-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết thông tin cá nhân",
                        Actived: false,
                        Code: "config008-enterprise-personal-info-detail",
                        Link: "/config/config008-enterprise-personal-info-detail",
                        Type: '',
                        LstChild: [],
                    },],
                },],
            }, {
                Name: "Quản trị hệ thống",
                Actived: false,
                Code: "sysmanage",
                Link: "/config/config005-enterprise-permission",
                Type: 'group',
                LstChild: [{
                    Name: "Vai trò",
                    Actived: false,
                    Code: "config004-enterprise-role",
                    Link: "/config/config004-enterprise-role",
                    Type: 'function',
                    LstChild: [],
                }, {
                    Name: "Phân quyền",
                    Actived: false,
                    Code: "config005-enterprise-permission",
                    Link: "/config/config005-enterprise-permission",
                    Type: 'function',
                    LstChild: [],
                }],
            }, {
                Name: "Quản lý đối tác",
                Actived: false,
                Code: "partnermanage",
                Link: "/config/config006-enterprise-partner",
                Type: 'group',
                LstChild: [{
                    Name: "Danh sách đối tác",
                    Actived: false,
                    Code: "config006-enterprise-partner",
                    Link: "/config/config006-enterprise-partner",
                    Type: 'function',
                    LstChild: [],
                }],
            },
            {
                Name: "Chính sách",
                Actived: false,
                Code: "config-policy",
                Link: "",
                Type: 'group',
                LstChild: [],
            },
            {
                Name: "Báo cáo",
                Actived: false,
                Code: "config-report",
                Link: "",
                Type: 'group',
                LstChild: [],
            },
            // {
            //     Name: "Mã khai quan",
            //     Actived: false,
            //     Code: "tax",
            //     Link: "/config/config009-tax-list",
            //     Type: 'group',
            //     LstChild: [
            // {
            //     Name: "Quản lý khai quan",
            //     Actived: false,
            //     Code: "config009-tax-list",
            //     Link: "/config/config009-tax-list",
            //     Type: 'function',
            //     LstChild: [],
            // },
            // {
            //     Name: "Phân nhóm khai quan",
            //     Actived: false,
            //     Code: "config010-tax-group",
            //     Link: "/config/config010-tax-group",
            //     Type: 'function',
            //     LstChild: [],
            // }
            //     ]
            // }
            {
                Name: "Quản lý Danh mục",
                Actived: false,
                Code: "enterprisecatalog",
                Link: "/config/config009-enterprise-country",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Quốc gia",
                        Actived: false,
                        Code: "config009-enterprise-country",
                        Link: "/config/config009-enterprise-country",
                        Type: 'function',
                        LstChild: []
                    },
                    {
                        Name: "Đơn vị hành chính",
                        Actived: false,
                        Code: "config010-enterprise-adminunit",
                        Link: "/config/config010-enterprise-adminunit",
                        Type: 'function',
                        LstChild: []
                    },







                    {
                        Name: "Tem nhãn",
                        Actived: false,
                        Code: "config012-enterprise-sticker",
                        Link: "/config/config012-enterprise-sticker",
                        Type: 'function',
                        LstChild: []
                    },
                ]
            }, 
        ]
    },
    //LOG
    {
        Code: 'log',
        Name: 'ĐIỀU PHỐI',
        Actived: true,
        Link: 'log/log001-hachi24h-list',
        Path: 'log',
        LoadChildren: () => import('../../p-log/p-log.module').then(m => m.PLogModule),
        ListMenu: [
            // {
            //     Name: "Dashboard",
            //     Actived: false,
            //     Code: "log003-dashboard",
            //     Link: "log/log001-hachi24h-list",
            //     Type: 'function',
            //     LstChild: [],
            // },
            {
                Name: "Sản phẩm",
                Actived: false,
                Code: "logProduct",
                Link: "/log/log001-hachi24h-list",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Hachi24h",
                        Actived: false,
                        Code: "log001-hachi24h-list",
                        Link: "/log/log001-hachi24h-list",
                        Type: 'function',
                        LstChild: [],
                    },],
            },
            {
                Name: "INBOUND",
                Actived: false,
                Code: "inbound",
                Link: "/log/log002-domestic-receiving-list",
                Type: 'group',
                LstChild: [{
                    Name: "Nhận hàng nội địa",
                    Actived: false,
                    Code: "log002-domestic-receiving-list",
                    Link: "/log/log002-domestic-receiving-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Nhận hàng nội địa",
                        Actived: false,
                        Code: "log002-domestic-receiving-detail",
                        Link: "/log/log002-domestic-receiving-detail",
                        Type: '',
                        LstChild: [],
                    }],
                },
                ],
            },
            {
                Name: "Chính sách",
                Actived: false,
                Code: "logPolicy",
                Link: "",
                Type: 'group',
                LstChild: [],
            },
            {
                Name: "Báo cáo",
                Actived: false,
                Code: "logReport",
                Link: "",
                Type: 'group',
                LstChild: [],
            },
        ]
    },
    //SALE
    {
        Code: 'sales',
        Name: 'Kinh doanh',
        Actived: true,
        Link: 'sale/sale001-policy-list',
        Path: 'sale',
        LoadChildren: () => import('../../p-sale/p-sale.module').then(m => m.PSaleModule),
        ListMenu: [
            // {
            //     Name: "Dashboard",
            //     Actived: false,
            //     Code: "sale004-dashboard",
            //     Link: "sale/sale001-policy-list",
            //     Type: 'function',
            //     LstChild: [],
            // }, 
            {
                Name: "Bán lẻ",
                Actived: false,
                Code: "pos",
                Link: "/sale/sale001-policy-list",
                Type: 'group',
                LstChild: [{
                    Name: "Thay đổi giá bán lẻ",
                    Actived: false,
                    Code: "sale001-policy-list",
                    Link: "/sale/sale001-policy-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Đợt Thay đổi giá bán lẻ",
                        Actived: false,
                        Code: "sale001-policy-detail",
                        Link: "/sale/sale001-policy-detail",
                        Type: '',
                        LstChild: [],
                    }],
                },
                {
                    Name: "Phiếu mua hàng",
                    Actived: false,
                    Code: "sale002-gift-voucher-list",
                    Link: "/sale/sale002-gift-voucher-list",
                    Type: 'function',
                    LstChild: [{
                        Name: "Chi tiết Đợt phát hành",
                        Actived: false,
                        Code: "sale002-gift-voucher-detail",
                        Link: "/sale/sale002-gift-voucher-detail",
                        Type: '',
                        LstChild: [],
                    }],
                },],
            },
            {
                Name: "Chính sách",
                Actived: false,
                Code: "salePolicy",
                Link: "/sale/sale004-policy",
                Type: 'group',
                LstChild: [],
            },
            {
                Name: "Báo cáo",
                Actived: false,
                Code: "saleReport",
                Link: "/sale/sale003-report",
                Type: 'group',
                LstChild: [
                    {
                        Name: "Báo cáo",
                        Actived: false,
                        Code: "sale003-report",
                        Link: "/sale/sale003-report",
                        Type: 'function',
                        LstChild: [],
                    },],
            },]
    }
]
